controller/__init__.py
import logging
from logging.handlers import RotatingFileHandler
from flask import Flask
from config import config_dict


# 设置日志(目的是将flask默认的日志和自定义的日志保存到文件中)
def setup_log(log_level):
    # 设置日志的记录等级
    logging.basicConfig(level=log_level)  # 根据配置类型设置日志等级

    # 创建日志记录器，指明日志保存的路径、每个日志文件的最大大小、保存的日志文件个数上限
    file_log_handler = RotatingFileHandler("logs/log", maxBytes=1024 * 1024 * 100, backupCount=10)
    # 创建日志记录的格式 日志等级 输入日志信息的文件名 行数 日志信息
    formatter = logging.Formatter('%(levelname)s %(pathname)s:%(lineno)d %(message)s')
    # 为刚创建的日志记录器设置日志记录格式
    file_log_handler.setFormatter(formatter)
    # 为全局的日志工具对象（flask app使用的）添加日志记录器
    logging.getLogger().addHandler(file_log_handler)


# 工厂函数: 由外界提供物料, 在函数内部封装对象的创建过程
def create_app(config_type):  # 封装web应用的创建过程
    # 根据类型取出对应的配置子类
    config_class = config_dict[config_type]
    app = Flask(__name__)
    app.config.from_object(config_class)

    # 注册蓝图对象  如果内容只在文件中使用一次, 最好在使用前才导入, 可以有效避免导入错误
    from controller.modules.home import home_blu
    app.register_blueprint(home_blu)
    from controller.modules.user import user_blu
    app.register_blueprint(user_blu)

    # 设置日志
    setup_log(config_class.LOG_LEVEL)

    return app

controller/modules/home/__init__.py
from flask import Blueprint

# 创建蓝图对象
home_blu = Blueprint("home", __name__)

# 让视图函数和主程序建立关联
from controller.modules.home.views import *

controller/modules/home/views.py
from flask import session, render_template, redirect, url_for, Response
from controller.modules.home import home_blu
from controller.utils.camera import VideoCamera

video_camera = None
global_frame = None


# 主页
@home_blu.route('/')
def index():
    # 模板渲染
    username = session.get("username")
    if not username:
        return redirect(url_for("user.login"))
    return render_template("index.html")


# 获取视频流
def video_stream():
    global video_camera
    global global_frame

    if video_camera is None:
        video_camera = VideoCamera()

    while True:
        frame = video_camera.get_frame()

        if frame is not None:
            global_frame = frame
            yield (b'--frame\r\n'
                   b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')
        else:
            yield (b'--frame\r\n'
                   b'Content-Type: image/jpeg\r\n\r\n' + global_frame + b'\r\n\r\n')


# 视频流
@home_blu.route('/video_viewer')
def video_viewer():
    # 模板渲染
    username = session.get("username")
    if not username:
        return redirect(url_for("user.login"))
    return Response(video_stream(),
                    mimetype='multipart/x-mixed-replace; boundary=frame')

controller/modules/user/__init__.py
from flask import Blueprint

# 创建蓝图对象
user_blu = Blueprint("user", __name__)

# 让视图函数和主程序建立关联
from controller.modules.user.views import *

controller/modules/user/views.py
from flask import session, redirect, url_for, request, render_template, jsonify
from controller.modules.user import user_blu
from controller.utils.camera import VideoCamera
from controller.utils.Mysql import Mysql
from controller.utils.controlmp import ControlMotor
from controller.utils.Face import Face
import time
import os

# 登录
@user_blu.route("/login", methods=["GET", "POST"])
def login():
    username = session.get("username")

    if username:
        return redirect(url_for("home.index"))
    if request.method == "GET":
        return render_template("login.html")
    # 获取参数
    username = request.form.get("username")
    password = request.form.get("password")
    # 校验参数
    if not all([username, password]):
        return render_template("login.html", errmsg="请完整填写账号和密码")

    # 校验对应的管理员用户数据
    if username == "admin" and password == "admin":
        # 验证通过
        session["username"] = username
        return redirect(url_for("home.index"))

    return render_template("login.html", errmsg="用户名或密码错误")

# 退出登录
@user_blu.route("/logout")
def logout():
    # 删除session数据
    session.pop("username", None)
    # 返回登录页面
    return redirect(url_for("user.login"))

# 门禁记录
@user_blu.route('/record')
def get_record():
    username = session.get("username")
    if username:
        db = Mysql()
        data = db.query()
        return render_template('record.html',recordlist=data)
    return redirect(url_for("user.login"))
    
#开关门
@user_blu.route('/ocdoor')
def ocdoor():
    username = session.get("username")
    if username:
        control = ControlMotor()
        control.forward(0.002,300)
        time.sleep(3)
        control.backward(0.002,300)
        return jsonify({"msg": "开门成功"}) 
    return redirect(url_for("user.login"))

#人员管理
@user_blu.route ('/permang')
def permang():
    username = session.get("username")
    if username:
        facelist = []
        facedict = dict()
        face = Face()
        face_tokens = face.detfaceset()
        for facetoken in face_tokens:
            user_id = face.detface(facetoken)
            facedict['facetoken'] = facetoken
            facedict['user_id'] = user_id
            facelist.append(facedict.copy())
        return render_template('permang.html',facelist=facelist)
    return redirect(url_for("user.login"))

#删除人脸信息
@user_blu.route ('/removeface')
def removeface():
    username = session.get("username")
    if username:
        face = Face()
        facetoken = request.args.get("facetoken")
        face_removed = face.removeface(facetoken)
        if face_removed == 1:
            return '<script>alert("删除成功");location.href="/permang";</script>'
        else:
            return '<script>alert("删除失败");location.href="/permang";</script>'
    return redirect(url_for("user.login"))
    
#添加成员
@user_blu.route ('/addface',methods=['GET', 'POST'])
def addface():
    username = session.get("username")
    if username:
        if request.method == 'POST':
            user_id = request.form.get("user")
            image_file = request.files.get('image')
            if not all([user_id, image_file]):
                return '<script>alert("添加失败，请完整填写姓名和上传照片！");location.href="/permang";</script>'
            image_name = image_file.filename
            mt_path = '/home/pi/monitors/faces/'
            facepath = os.path.join(mt_path,image_name)
            image_file.save(facepath)
            face = Face()
            facetoken = face.detect(facepath)
            if facetoken:
                userid = face.addface(facetoken,user_id)
                if userid == user_id:
                    return '<script>alert("添加成功！");location.href="/permang";</script>'
                return '<script>alert("添加失败，请重新添加！");location.href="/permang";</script>'
            return '<script>alert("添加失败，未检测到人脸，请重新添加！");location.href="/permang";</script>'
        return redirect(url_for("user.permang"))
    return redirect(url_for("user.login"))
    

controller/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>监控系统</title>
    <style>
        body {
            background-color: #484856;
        }

    </style>
</head>
<body>
<h1 align="center" style="color: whitesmoke;">家庭门禁系统</h1>
<div class="top">
    <div class="recorder" id="recorder" align="center">
        <button onclick="window.location.href = 'record'">门禁记录</button>
        <button onclick="window.location.href = 'permang'">人员管理</button>
        <button onclick="ocdoor()">开/关门</button>
        <input type="button" class="btn" value="退出登录" onclick="javascrtpt:window.location.href='{{ url_for('user.logout') }}'"/>
    </div>
</div>
<div align="center"><img id="video" src="{{ url_for('home.video_viewer') }}" width="60%" vspace="20"></div>
</body>
<script>
function ocdoor() {
  var url = "{{ url_for("user.ocdoor") }}"
  var request = new XMLHttpRequest();
  request.open("GET", url);
  request.send();
  alert("芝麻开门");
}
</script>
</html>

controller/templates/login.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script type="application/x-javascript"> addEventListener("load", function () {
        setTimeout(hideURLbar, 0);
    }, false);

    function hideURLbar() {
        window.scrollTo(0, 1);
    } </script>
    <link href="../static/css/style.css" rel='stylesheet' type='text/css'/>
    <!--字体-->
    <link href='http://fonts.useso.com/css?family=PT+Sans:400,700,400italic,700italic|Oswald:400,300,700'
          rel='stylesheet' type='text/css'>
    <link href='http://fonts.useso.com/css?family=Exo+2' rel='stylesheet' type='text/css'>
    <!--//js-->
    <script src="http://ajax.useso.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
</head>
<body>
<script>$(document).ready(function (c) {
    $('.close').on('click', function (c) {
        $('.login-form').fadeOut('slow', function (c) {
            $('.login-form').remove();
        });
    });
});
</script>
<!--SIGN UP-->
<h1>家庭监控系统</h1>
<div class="login-form">
    <div class="close"></div>
    <div class="head-info">
        <label class="lbl-1"> </label>
        <label class="lbl-2"> </label>
        <label class="lbl-3"> </label>
    </div>
    <div class="clear"></div>
    <div class="avtar">
        <img src="../static/images/avtar.png"/>
    </div>
    <form method="post" action="{{ url_for("user.login") }}">
        <input type="text" class="text" name="username" value="Username" onfocus="this.value = '';"
               onblur="if (this.value == '') {this.value = 'Username';}">
        <div class="key">
            <input type="password" name="password" value="Passowrd" onfocus="this.value = '';"
                   onblur="if (this.value == '') {this.value = 'Password';}">
        </div>
        <div class="signin">
            <input type="submit" value="登录">
            {% if errmsg %} {# 判断是否有错误信息 #}

                <div class="error_tip" style="display: block;color: red">{{ errmsg }}</div>

            {% endif %}
        </div>
    </form>

</div>

</body>
</html>

controller/templates/permang.html
<!DOCTYPE html>
<html lang="cn-zh">
<head>
    <meta charset="UTF-8">
    <title>人员管理</title>
    <style type="text/css">
        *{
            margin: 10;
            padding: 0;
        }
        #upBox{
            text-align: center;
            width:500px;
            padding: 20px;
            border: 1px solid #666;
            margin: auto;
            margin-top: 150px;
            margin-bottom: 200px;
            position: relative;
            border-radius: 10px;s
		}
        #btn{
            outline: none;
            width: 100px;
            height: 30px;
            background: cornflowerblue;
            border: 1px solid cornflowerblue;
            color: white;
            cursor: pointer;
            margin-top: 30px;
            border-radius: 5px;
        }
    </style>
</head>

<body>
    <center>
        <h1>家庭成员列表</h1>
        <hr>
        <table border="1px" width="800px">
            <tr style="text-align:center">
                <th>人脸符记</th>
                <th>姓名</th>
                <th>操作</th>
            </tr>
            {% for i in facelist %}
            <tr style="text-align:center">
                <td>{{ i.facetoken }}</td>
                <td>{{ i.user_id }}</td>
                <td><a href="javascript:if(window.confirm('确认删除？')){window.location.href='/removeface?facetoken={{ i.facetoken }}'}">删除</a></td>
            </tr>
            {% endfor %}
        </table>
    </center>

    <form action="{{ url_for("user.addface") }}" method="post" enctype="multipart/form-data" id="upBox">
        <p><font size="4">新增家庭成员</font></p>
        <div class="form-group">
            <label class="sr-only" for="name">姓名:</label>
            <input type="text" class="form-control" name="user" placeholder="请输入姓名">
        </div>
        <p></p>
        <div class="form-group">
            <label class="sr-only" for="inputfile">上传照片:</label>
            <input type="file" name="image" multiple accept="image/png,image/jpg,image/JPEG"/>
        </div>
        <input type="submit" value="确认添加" id="btn">
    </form>
    
</body>
</html>

controller/templates/record.html
<!DOCTYPE html>
<html lang="cn-zh">
<head>
    <meta charset="UTF-8">
    <title>门禁数据列表</title>
</head>

<body>
    <center>
    <h1>家庭门禁记录</h1>
    <hr>
    <table border="1px" width="800px">
        <tr style="text-align:center">
            <th>时间日期</th>
            <th>人脸符记</th>
            <th>相似度</th>
            <th>人脸名</th>
            <th>人名</th>
        </tr>
        {% for i in recordlist %}
        <tr style="text-align:center">
            <td>{{ i.date_time }}</td>
            <td>{{ i.face_token }}</td>
            <td>{{ i.confidence }}</td>
            <td>{{ i.face_name }}</td>
            <td>{{ i.user_id }}</td>
        </tr>
        {% endfor %}

    </table>
    </center>

</body>
</html>